Shelter deduction
PolicyEngine/openfisca-us pull request #122
Opened 2021-09-10 23:16 UTC by nmrodelo

#74 add shelter deduction parameters by state.

2021-09-11 07:22 UTC, nikhilwoodruff reviewed
Looks good @nmrodelo - could you try using [this YAML formatter](https://pypi.org/project/yamlfmt/) on the parameter file? Seems like it could save time

2021-09-13 18:28 UTC, MaxGhenis requested changes

2021-09-13 18:28 UTC, MaxGhenis commented on openfisca_us/parameters/benefit/SNAP/shelter_deduction.yaml
> +shelter_deduction:
delete lines 3-4 and unindent accordingly

2021-09-13 18:28 UTC, MaxGhenis commented on openfisca_us/parameters/benefit/SNAP/shelter_deduction.yaml
> +description: Maximum Monthly Shelter Deduction by State and Household Size
```suggestion
description: Maximum SNAP shelter deduction
```

2021-09-18 18:26 UTC, MaxGhenis approved these changes

2021-09-18 18:26 UTC, merged